server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8090/grs_security
          predicates:
            - Path=/grs_security/auth/**
        - id: grs-service
          uri: http://localhost:8081/grs_server
          predicates:
            - Path=/grs_server/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
management:
  endpoints:
    web:
      exposure:
        include: "*"